### ISSUE TITLE
Containerize Sage Bot

### ISSUE THREAD

**Issue by macizo-hook** [macizo-hook/discord-sage-bot#8]
I think this would be useful for anyone interested in running the bot on Kubernetes, or Lambda, or something. This will speed up development for me as well in some cases.

**Comment by Marsh-sudo** [comment]
Is it necessary for it to be containerized using only Kubernetes or also docker is allowed?

**Comment by macizo-hook** [comment]
@Marsh-sudo docker is cool.

**Comment by Marsh-sudo** [comment]
Assign it to me then...i will use docker

**Comment by Marsh-sudo** [comment]
Are there any packages installed needed for the program needed to run and if so kindly push the requirements.txt file for one to know which packages kindly

**Comment by macizo-hook** [comment]
@Marsh-sudo good callout: See the following https://github.com/macizo-hook/discord-sage-bot/commit/58a24bf8b3ec7d86bb54492e73726efa1dad9117

**Comment by Marsh-sudo** [comment]
Where did you get the `OPEN_API_KEY` am not able to run the program without it kindly

**Comment by macizo-hook** [comment]
1. Go to the OpenAI website: Navigate to https://platform.openai.com/ in your web browser.
2. Sign up or log in.
3. Access the API keys page -  https://platform.openai.com/account/api-keys.
4. Retrieve or generate your API key.

**Comment by macizo-hook** [comment]
@Marsh-sudo you nailed it. Good job!

**Comment by Marsh-sudo** [comment]
Thank you so much and loved to help 🫡
